### ISSUE TITLE
Transactions Showing Old Money

### ISSUE THREAD

**Issue by UnitedMarcus** [NL-Cosmo/cosmo#44]
**Describe the bug**
Transactions Showing Old Money

**To Reproduce**
1. Go to Player Details
2. Select Character
3. Click on total money
4. then transactions

**Expected behavior**
If you look at bottom page 1 is old transactions and page 133 are recent
it should be other way round

**Screenshots**
https://file.coffee/u/JqPMmtD90XlXcCknS7H7H.png
https://file.coffee/u/xDjemvN4Y9YIkRfrec-HH.png

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 11

**Smartphone (please complete the following information):**
N/A
**Additional context**
N/A

**Comment by NinjaLabs-Dev** [comment]
Good catch, will update and also add a timestamp as that tbh should be there.

**Comment by NinjaLabs-Dev** [comment]
Fixed in `64d272d`
